/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0RXSRC_UART_RX 0x00u /*!<@brief UART 0 receive data source select: UART0_RX pin */
#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */

/*! @name PORTE19 (number 21), BOOT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_BOOT_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_BOOT_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_BOOT_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_BOOT_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_BOOT_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTE20 (number 25), DEBUG_UART_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_DEBUG_UART_RX_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_DEBUG_UART_RX_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_DEBUG_UART_RX_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTE21 (number 26), DEBUG_UART_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_DEBUG_UART_TX_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_DEBUG_UART_TX_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_DEBUG_UART_TX_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTE29 (number 37), LED_GREEN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_GREEN_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_GREEN_GPIO_PIN_MASK (1U << 29U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LED_GREEN_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_LED_GREEN_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_LED_GREEN_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*! @name PORTE30 (number 38), LED_RED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_RED_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_RED_GPIO_PIN_MASK (1U << 30U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LED_RED_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_LED_RED_PIN 30U                   /*!<@brief PORT pin number */
#define BOARD_LED_RED_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORTA18 (number 72), EXTAL0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_EXTAL0_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_EXTAL0_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_EXTAL0_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTA19 (number 73), XTAL0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_XTAL0_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_XTAL0_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_XTAL0_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name RESET_b (number 74), RESET
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/*!
 * @brief IEEE 1588 timestamp clock source select: External bypass clock (ENET_1588_CLKIN) */
#define SOPT2_TIMESRC_ENET 0x03u

/*! @name PORTE26 (number 47), J15[B47]/SPI0_PCS1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_ENET_1588_CLKIN_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_ENET_1588_CLKIN_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_ENET_1588_CLKIN_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTA11 (number 63), ETH_POWER
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_ETH_POWER_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_ETH_POWER_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_ETH_POWER_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_ETH_POWER_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_ETH_POWER_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_ETH_pins(void);

/*! @name PORTB2 (number 83), I2C_SCL
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_I2C_PINS_I2C_SCL_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_I2C_PINS_I2C_SCL_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_I2C_PINS_I2C_SCL_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTB3 (number 84), I2C_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_I2C_PINS_I2C_SDA_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_I2C_PINS_I2C_SDA_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_I2C_PINS_I2C_SDA_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_I2C_Pins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_JTAG(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_POWER_Pins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
